root: ./

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    buy-store-and-stake-pokt: pokt/README.md
    resources/references/supported-blockchains: supported-blockchains.md
    v0/glossary: learn/glossary.md
    v0/protocol: learn/protocol/README.md
    v0/protocol/security: learn/protocol/security.md
    v0/protocol/servicing: learn/protocol/servicing.md
    v0/economics: learn/economics/README.md
    v0/economics/monetary-policy: learn/economics/monetary-policy.md
    v0/economics/monetary-policy/monetary-phases: learn/economics/monetary-policy.md
    v0/economics/monetary-policy/application-burn-rate: learn/economics/monetary-policy.md
    v0/economics/monetary-policy/pokt-inflation: learn/economics/monetary-policy.md
    v0/economics/the-web3-infra-trap: learn/economics/README.md
    v0/economics/decentralizing-infrastructure: learn/vision.md
    v0/economics/pokt-token-economics: learn/economics/token.md
    v0/economics/pokt-token-economics/token-staking: learn/economics/token.md
    v0/economics/pokt-token-economics/app-economics: learn/economics/apps.md
    v0/economics/pokt-token-economics/app-economics/stability-adjustment: learn/economics/apps.md
    v0/economics/pokt-token-economics/app-economics/participation-rate: learn/economics/apps.md
    v0/economics/pokt-token-economics/app-economics/base-throughput: learn/economics/apps.md
    v0/economics/pokt-token-economics/node-economics: learn/economics/nodes.md
    v0/economics/pokt-token-economics/node-economics/cost-to-nodes: learn/economics/nodes.md
    v0/economics/pokt-token-economics/node-economics/economic-security: learn/economics/nodes.md
    v1/v1-overview: learn/future/README.md
    v1/consensus: learn/future/consensus.md
    v1/peer-to-peer: learn/future/peer-to-peer.md
    v1/persistence: learn/future/persistence.md
    v1/utility: learn/future/utility.md
    pokt-accounts-and-transactions: integrate/accounts-transactions/README.md
    pokt-accounts-and-transactions/address-generation-and-validation: integrate/accounts-transactions/account-generation-validation.md
    pokt-accounts-and-transactions/deposit-processing-and-verification: integrate/accounts-transactions/transaction-verification.md
    pokt-accounts-and-transactions/transaction-construction-and-offline-signature: integrate/accounts-transactions/transaction-construction.md
    paths/node-runner: node/README.md
    paths/node-runner/zero-to-node: node/tutorials/zero-to-node/README.md
    paths/node-runner/zero-to-node/server-setup: node/tutorials/zero-to-node/server-setup.md
    paths/node-runner/zero-to-node/software-install: node/tutorials/zero-to-node/software-install.md
    paths/node-runner/zero-to-node/pocket-config: node/tutorials/zero-to-node/pocket-config.md
    paths/node-runner/zero-to-node/proxy-config: node/tutorials/zero-to-node/proxy-config.md
    paths/node-runner/zero-to-node/going-live: node/tutorials/zero-to-node/going-live.md
    paths/node-runner/maximize-your-pokt-earnings: node/faq.md
    paths/app-developer: use/get-endpoint.md
    paths/app-developer/use-ethersjs: use/get-endpoint.md
    paths/contributor: community/trophies/contributors.md
    paths/shepherd: community/trophies/community-shepherds.md
    paths/governor: community/trophies/README.md
    paths/governor/claim-your-vote: community/trophies/README.md
    paths/governor/claim-your-vote/app-developer-path: community/trophies/app-developers.md
    paths/governor/claim-your-vote/community-shepherd-path: community/trophies/community-shepherds.md
    paths/governor/claim-your-vote/governor-path: community/trophies/contributors.md
    paths/governor/claim-your-vote/node-runner-path: community/trophies/node-runners.md
    paths/governor/submit-a-proposal: community/governance/proposals.md
    paths/governor/submit-a-proposal/pip-pocket-improvement-proposal: community/governance/proposals.md
    paths/governor/submit-a-proposal/pep-pocket-ecosystem-proposal: community/governance/proposals.md
    paths/governor/submit-a-proposal/pup-parameter-update-proposal: community/governance/proposals.md
    resources/contact-us: more-info.md
    resources/faq/app-integration: use/get-endpoint.md
    resources/faq/pricing-and-economics: learn/economics/faq.md
    resources/faq/node-configuration: node/faq.md
    resources/faq/node-troubleshooting: node/faq.md
    resources/faq/wpokt: pokt/wpokt.md
    resources/references/seeds: node/seeds.md
    resources/references/protocol-parameters: learn/protocol-parameters.md
    resources/references/pokt-denominations: learn/economics/token.md
    resources/public-rpc-endpoints: use/public-rpc/README.md
    resources/public-rpc-endpoints/avalanche-avax-metamask: use/public-rpc/avax.md
    resources/public-rpc-endpoints/binance-smart-chain-bsc-metamask: use/public-rpc/bsc.md
    resources/public-rpc-endpoints/dfk-chain-metamask: use/public-rpc/dfk-chain.md
    resources/public-rpc-endpoints/ethereum-eth-metamask: use/public-rpc/ethereum.md
    resources/public-rpc-endpoints/evmos-metamask: use/public-rpc/evmos.md
    resources/public-rpc-endpoints/fuse-metamask: use/public-rpc/fuse.md
    resources/public-rpc-endpoints/harmony-metamask: use/public-rpc/harmony.md
    resources/public-rpc-endpoints/iotex-metamask: use/public-rpc/iotex.md
    resources/public-rpc-endpoints/polygon-metamask: use/public-rpc/polygon.md
    resources/public-rpc-endpoints/xdai-metamask: use/public-rpc/gnosis-chain.md
    resources/public-rpc-endpoints/conquest.eth: use/dapps/conquest-eth.md
    resources/public-rpc-endpoints/dark-forest: use/dapps/dark-forest.md
    resources/public-rpc-endpoints/mycrypto: use/dapps/mycrypto.md
    resources/public-rpc-endpoints/rotki: use/dapps/rotki.md
    test1: supported-blockchains.md
    test2: ./supported-blockchains.md
    test3: ./home/supported-blockchains.md
